model = "parts/capsule/capsule.fbx"

name = "Crew Can 01"
country = "United States"
manufacturer = "Rocket Factory"
description = "Crew goes in and hopefully out later in the mission"


[p_root]
	mass = 400.0


[[machine]]
	id = "capsule"
	script = "core:machines/capsule.lua"	
