model = "parts/engine/engine.fbx"

name = "Fire Tube Mk. 1"
country = "United States"
manufacturer = "Rocket Factory"
description = "Generates thrust"


[p_root]
	mass = 400.0


[[machine]]
	id = "main_engine"
	script = "core:machines/engine.lua"
	thrust = 100.0

