[star]
	name = "Sun"
	mass = 1.98847e30
	radius = 695_508_000.0


[[element]]
	name = "Earth"
	config = "planets/earth/config.toml"

	smajor_axis = 149_000_000_000
	eccentricity = 0.0
	inclination = 0.0
	periapsis_argument = 0.0
	asc_node_longitude = 0.0
	mean_at_epoch = 544.0

	rotation_period = 24.0
	#rotation_period = 1000000000.0
	rotation_at_epoch = 800.0
	north_pole_declination = 65.64
	north_pole_right_ascension = 266.86
