
description = "A very cool testing vehicle"
packages = ["test_parts"]
part_id = 4
piece_id = 4

[[part]]	
	id = 1
	proto = "test_parts:parts/capsule/part_capsule.toml"
[[piece]]
	root = true
	id = 1		
	part = 1
	node = "p_root"
	[piece.pos]
		x = 0.0
		y = 0.0
		z = 0.0
	[piece.rot]
		x = 0.0
		y = 0.0
		z = 0.0
		w = 1.0 		
