[vehicle_prototype]
	description = "A very cool testing vehicle"
	packages = ["test_parts"]
	part_id = 2
	piece_id = 2
	
	[[part]]	
		id = 1
		proto = "test_parts:parts/capsule/part_capsule.toml"
	[[part]]
		id = 2
		proto = "test_parts:parts/engine/part_engine.toml" 		

	# On a vehicle prototype, pieces without parts are impossible
	# these only exist on real vehicles in the world
	[[piece]]
		root = true
		id = 1		
		part = 1
		node = "p_root"
		[piece.pos]
			x = 2.0
			y = 0.0
			z = 0.0
		[piece.rot]
			x = 0.0
			y = 0.0
			z = 0.0
			w = 1.0 		
	[[piece]]
		id = 2
		part = 2
		node = "p_root"
		[piece.pos]
			x = 2.0
			y = 0.0
			z = -2.0
		[piece.rot]
			x = 0.0
			y = 0.0
			z = 0.0
			w = 1.0
		[piece.link]
			to = 1
			welded = false
			type = "core:links/simple_link.lua"
			[piece.link.pfrom]
				x = 0.0
				y = 0.0
				z = 1.0
			[piece.link.pto]
				x = 0.0
				y = 0.0
				z = -1.0
	
