name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libx11-dev xorg-dev libgl1-mesa-dev
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: configure twice
      run: |
        sudo cmake .
        sudo cmake.
    - name: make
      env:
        CC: gcc-8
        CXX: g++-8  
      run: sudo cmake --build .
