name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxrandr-dev libxinerama-dev libxcursor1 libxi-dev
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: configure
      run: cmake .
    - name: make
      run: cmake --build .
